services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/traefik/tls.yml"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/localhost.crt:/traefik/localhost.crt:ro
      - ./certs/localhost.key:/traefik/localhost.key:ro
      - ./traefik-tls.yml:/traefik/tls.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    networks:
      - traefik

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - traefik

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mail.localhost`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    networks:
      - traefik

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PASSWORD=dev          # mot de passe pour accéder à l'UI
      - SUDO_PASSWORD=dev     # sudo dans le terminal intégré
      - PROXY_DOMAIN=code.localhost
      - DEFAULT_WORKSPACE=/workspace
    volumes:
      - ./code/workspace:/workspace
      - ./code/code-server-config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=Host(`code.localhost`)"
      - "traefik.http.services.code.loadbalancer.server.port=8443"
    networks:
      - traefik
    profiles:
      - ide




volumes:
  portainer_data:
  code-server-config:

networks:
  traefik:
    external: true
